# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goasitop < Formula
  desc "Apple Silicon Monitor Top written in Go Lang"
  homepage "https://github.com/context-labs/goasitop"
  version "0.0.6"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/context-labs/goasitop/releases/download/v0.0.6/goasitop_0.0.6_darwin_arm64.tar.gz"
    sha256 "dbecbf3e695f96138ebc9c84f4cb42b40308254901942e0caafc5dbe05f298c4"

    def install
      bin.install "goasitop"
    end
  end

  def caveats
    <<~EOS
      goasitop requires macOS 12+, and runs only on Apple Silicon.
    EOS
  end
end
