# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goasitop < Formula
  desc "Apple Silicon Monitor Top written in Go Lang"
  homepage "https://github.com/context-labs/goasitop"
  version "0.0.9"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/context-labs/goasitop/releases/download/v0.0.9/goasitop_0.0.9_darwin_arm64.tar.gz"
    sha256 "aafaa4eaaba1502d4faeb95c91824f48f22cc6743157996604179a8081f74cc5"

    def install
      bin.install "goasitop"
    end
  end

  def caveats
    <<~EOS
      goasitop requires macOS 12+, and runs only on Apple Silicon.
    EOS
  end
end
