# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goasitop < Formula
  desc "Apple Silicon Monitor Top written in Go Lang"
  homepage "https://github.com/context-labs/goasitop"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/context-labs/goasitop/releases/download/v0.1.0/goasitop_0.1.0_darwin_arm64.tar.gz"
    sha256 "b4f417c01e1e1aa4bf841b127d1fb982fe9789cf00a5fe965104dbf4cfab83a1"

    def install
      bin.install "goasitop"
    end
  end

  def caveats
    <<~EOS
      goasitop requires macOS 12+, and runs only on Apple Silicon.
    EOS
  end
end
