# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mactop < Formula
  desc "Apple Silicon Monitor Top written in Go Lang"
  homepage "https://github.com/context-labs/mactop"
  version "0.2.7"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/context-labs/mactop/releases/download/v0.2.7/mactop_0.2.7_darwin_arm64.tar.gz"
    sha256 "893b00e4ec43b38cb0d8c2d9c5d21c299331214eb7889ef7fb660a4115d4b793"

    def install
      bin.install "mactop"
    end
  end

  def caveats
    <<~EOS
      mactop requires macOS 12+, and runs only on Apple Silicon.
    EOS
  end
end
